added repository creation if packages built

diff --git a/scripts/udba-builder b/scripts/udba-builder
--- a/scripts/udba-builder
+++ b/scripts/udba-builder
@@ -1,4 +1,7 @@
 #! /bin/bash
+# if there is some issue script will nto output required string and 
+# udba will show failure
+set -e
 PACKAGE_NAME=$(echo $1|sed -e 's/udba-//g')
 cd /var/tmp/udba-build-root/${PACKAGE_NAME}/
 HOME=$(pwd)
@@ -19,23 +22,10 @@ cat << E__O__F > .rpmmacros
 %_specdir %(echo "`pwd`")
 %_srcrpmdir %(echo "`pwd`/srpmdir")
 E__O__F
-/usr/bin/rpmbuild -ba *-g*G02.spec
-echo "###########################################"
-echo "########## First part of build done########"
-echo "###########################################"
-find "${HOME}/rpmdir/${UM}"  -type f -ls
-
-echo "###########################################"
-echo "####### Press enter to continue build #####"
-echo "###########################################"
-
-#read pause
-/usr/bin/rpmbuild -ba x11-video-*G02.spec
-echo "###########################################"
-echo "############### All Done ##################"
-echo "###########################################"
-echo 
-echo "Now install files from ${HOME}/rpmdir/${UM}"
-echo "Files:"
-find "${HOME}/rpmdir/${UM}"  -type f -ls
-sleep 10
+for rpmspec in *.spec; do
+	# nothing smart here really...
+	/usr/bin/rpmbuild -ba ${rpmspec}
+done
+find "/srv/repos/${PACKAGE_NAME}/${UM}"  -type f -ls
+sleep 1
+echo "UDBA: Build Complete"
